services:
  db:
    restart: unless-stopped
    image: postgres:18
    env_file:
      - ./env/db.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  init-db:
    build:
      context: .
      dockerfile: db/Dockerfile
    env_file:
      - ./env/db.env
      - ./env/reddit_api.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy

  scrape:
    restart: unless-stopped
    build:
      context: .
      dockerfile: scrape/Dockerfile
    env_file:
      - ./env/reddit_api.env
      - ./env/db.env
      - ./env/openrouter_api.env
    depends_on:
      db:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully

  next:
    restart: unless-stopped
    build:
      context: ./next
      dockerfile: Dockerfile
    env_file:
      - ./env/db.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully

  caddy:
    restart: unless-stopped
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - next

volumes:
  pgdata:
  caddy_data:
  caddy_config:
