AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda

  Sample SAM Template for lambda

Parameters:
  SubnetIds:
    Type: CommaDelimitedList
    Description: Public subnet IDs for Lambda VPC config
  SecurityGroupId:
    Type: String
    Description: Security group ID for Lambda VPC config

Globals:
  Function:
    Timeout: 30
    VpcConfig:
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds:
        - !Ref SecurityGroupId

Resources:
  QueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: query/
      Handler: src/app.lambdaHandler
      Runtime: nodejs24.x
      Environment:
        Variables:
          DB_HOST: "{{resolve:ssm:/uniwatch/DB_HOST}}"
          DB_PORT: "{{resolve:ssm:/uniwatch/DB_PORT}}"
          DB_NAME: "{{resolve:ssm:/uniwatch/DB_NAME}}"
          DB_USER: "{{resolve:ssm:/uniwatch/DB_USER}}"
          DB_PASS: "{{resolve:ssm:/uniwatch/DB_PASS}}"
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /query
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/app.ts
        Loader:
          - .pem=text
        Target: es2022
        Minify: false
        Sourcemap: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  QueryApi:
    Description: "API Gateway endpoint URL for Prod stage for Query function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/query/"
  QueryFunction:
    Description: "Query Lambda Function ARN"
    Value: !GetAtt QueryFunction.Arn
  QueryFunctionIamRole:
    Description: "Implicit IAM Role created for Query function"
    Value: !GetAtt QueryFunctionRole.Arn
